---
name: Deploy on push
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version-file: "package.json"

      - name: Install Dependencies
        run: npm ci --production

      - name: Lint Code Base
        uses: super-linter/super-linter@main
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          JAVASCRIPT_DEFAULT_STYLE: prettier
          VALIDATE_JAVASCRIPT_STANDARD: false

      - name: Test Code
        run: npm run test --coverage

  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Build and Deploy with gh-pages
        run: |
          git remote set-url origin "${GIT_URL}"
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GIT_URL: https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
